// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAbwmQUT-X4owR39COXwPaFU-1O2l1nn0',
    appId: '1:850512705778:web:b4c6c732ebceb94336786b',
    messagingSenderId: '850512705778',
    projectId: 'dalel-b49d7',
    authDomain: 'dalel-b49d7.firebaseapp.com',
    storageBucket: 'dalel-b49d7.firebasestorage.app',
    measurementId: 'G-Z0G3CX1VNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvT97Mk7tgeako1S6Q0x1jdU2MVI8xUK8',
    appId: '1:850512705778:android:028a22c14376751236786b',
    messagingSenderId: '850512705778',
    projectId: 'dalel-b49d7',
    storageBucket: 'dalel-b49d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQfpikxjGKuflmtPTRvc1LXg6VygftYtU',
    appId: '1:850512705778:ios:dae57124fc228ad736786b',
    messagingSenderId: '850512705778',
    projectId: 'dalel-b49d7',
    storageBucket: 'dalel-b49d7.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQfpikxjGKuflmtPTRvc1LXg6VygftYtU',
    appId: '1:850512705778:ios:dae57124fc228ad736786b',
    messagingSenderId: '850512705778',
    projectId: 'dalel-b49d7',
    storageBucket: 'dalel-b49d7.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAbwmQUT-X4owR39COXwPaFU-1O2l1nn0',
    appId: '1:850512705778:web:8e64bab5d151d4d236786b',
    messagingSenderId: '850512705778',
    projectId: 'dalel-b49d7',
    authDomain: 'dalel-b49d7.firebaseapp.com',
    storageBucket: 'dalel-b49d7.firebasestorage.app',
    measurementId: 'G-R1MXCYEDPX',
  );

}